# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
[build]
  publish = "packages/graphiql"

  # Default build command.
  command = "pnpm install --frozen-lockfile && pnpm build && pnpm build-docs"
  environment = { YARN_FLAGS = "--frozen-lockfile"}
