packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'examples/monaco-graphql-webpack'
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!**/__test__/**'
