name: License Check
on:
  pull_request:
    paths:
      - 'pnpm.lock'

jobs:
  check:
    name: License Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.5
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: License Check
        run: pnpm license-check
