name: Lint & Build PR
on:
  pull_request:
    types: [opened, synchronize]
    # TODO: ignore this after setting up a separate task to link markdown
    # and to ignore eslint/prettier issues in examples
    # paths-ignore:
    #   - '**.md'
    #   - 'examples'
    #   - '!examples/monaco-graphql-webpack'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.5
          
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: TypeScript Build
        run: pnpm build

      - name: ESLint
        run: pnpm lint
