name: E2E
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  e2e:
    name: Cypress E2E Suite
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.5
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Cache Cypress Binary
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: binary-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Run E2E suite
        run: pnpm e2e
