name: Build & Test PR w/ GraphQL Regressions
on:
  push:
    # only on merge to main.
    # it's rare that this workflow would
    # show us an error, but when it does it's important!
    branches:
      - main
    # don't run this regression suite if we don't need to
    paths-ignore:
      - '**.md'
      - 'examples'
      - '!examples/monaco-graphql-webpack'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # test all peer ranges
        release: ['^15.5.0', '^15.8.0', 'latest']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.5
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 19

      - name: Force GraphQL ${{ matrix.release }} solution
        run: pnpm repo:resolve graphql@${{ matrix.release }}

      - run: pnpm install --frozen-lockfile

      - name: Unit Tests
        run: pnpm test:ci

      - name: Cypress
        run: pnpm e2e
