name: Test PR
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - 'examples'
      - '!examples/monaco-graphql-webpack'
jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.5
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Run Build
        run: pnpm build
      - name: Run Unit Tests
        run: pnpm test --coverage

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
